name: Wex TVBox 自动同步过滤


on:

  # 每天北京时间 04:00 自动运行
  schedule:
    - cron: "0 20 * * *"


  # 支持手动运行
  workflow_dispatch:



permissions:

  contents: write



jobs:


  sync:


    runs-on: ubuntu-latest



    steps:


      # 拉取仓库

      - name: Checkout

        uses: actions/checkout@v4



      # 安装 Python

      - name: Setup Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.x"



      # 运行过滤程序

      - name: Run filter

        run: |

          python filter.py



      # 检查生成结果

      - name: Check files

        run: |

          ls -lh

          echo "fish.json 检查"

          head -c 200 fish.json



      # 自动提交

      - name: Commit and Push

        run: |

          git config user.name "github-actions"

          git config user.email "github-actions@github.com"


          git add .


          git commit -m "自动更新Wex TVBox配置" || echo "没有变化"


          git push
