name: fish自动同步


on:

  workflow_dispatch:


  schedule:

    - cron: "0 */6 * * *"



permissions:

  contents: write



jobs:

  sync:


    runs-on: ubuntu-latest



    steps:


    - name: 拉取仓库

      uses: actions/checkout@v4

      with:

        token: ${{ secrets.GITHUB_TOKEN }}



    - name: 执行过滤

      run: |

        python filter.py



    - name: 保存更新

      run: |


        git config --global user.name "github-actions"

        git config --global user.email "actions@github.com"


        git add fish.json


        git diff --cached --quiet && exit 0


        git commit -m "自动同步 fish 接口"


        git push
